services:
  db:
    image: postgres:17
    container_name: postgres-container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: crm
    volumes:
      - pgdata:/var/lib/postgresql/data # Persistent data storage
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
volumes:
  pgdata:
